id = "hologram"
name = "Hologram"
version = "0.1.0"
schema_version = 1
authors = ["Luka Tchelidze <lukachelidze3008@gmail.com>"]
description = "HOLO template language support for the Hologram framework: syntax highlighting, indentation, and formatting via mix format."
repository = "https://github.com/Null-logic-0/zed-hologram"

[grammars.holo]
repository = "https://github.com/Null-logic-0/tree-sitter-holo"
rev = "c1c1b5a99bafcb91fe60e95be9b8cb0819769b7e"
